# Generated by Django 5.1.2 on 2024-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_password_alter_endereco_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='telefone_secundario',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_apresentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$grZkei1gAaR4YqmaWVFPzr$Lsisz57/RjnKnNUO6cQ/SqbzzooLMDtdAwAcqN/F1xI=', max_length=200),
        ),
    ]
