# Generated by Django 5.1.2 on 2024-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_telefone_secundario_empresa_telefone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precoprodutoempresa',
            old_name='descricao_personalizada',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao_padrao',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$cKJJJgsUZKljkotDx64Utp$EeS4j0L+JQ0eNChca6c+Q/wQGdItHspQEIpJR4VTY1w=', max_length=200),
        ),
    ]
